name: CI
on: workflow_dispatch

jobs:
  build: # 自定义名称
    runs-on: ubuntu-latest # 运行在虚拟机环境ubuntu-latest

    steps:
      - run: |
          pwd
          ls -a ~
          whereis vercel

      - name: Setup Node
        uses: actions/setup-node@v3.1.1
        with:
          node-version: '16'
#          cache: yarn

      - run: |
          whereis vercel
          pwd
          ls -a ~
          ls -a ~/*
          

